'use strict';
import * as vscode from 'vscode';

interface QuickPickItemWithURL extends vscode.QuickPickItem {
    url: string;
}

export class ReferenceProvider {
    private readonly kag3ReferenceMap: QuickPickItemWithURL[] = [
        { label: "animstart", description: "アニメーションの開始(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#animstart" },
        { label: "animstop", description: "アニメーションの停止(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#animstop" },
        { label: "autowc", description: "自動ウェイト(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#autowc" },
        { label: "backlay", description: "レイヤ情報の表ページから裏ページへのコピー(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#backlay" },
        { label: "bgmopt", description: "BGM の設定(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#bgmopt" },
        { label: "button", description: "グラフィカルボタン(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#button" },
        { label: "call", description: "サブルーチンの呼び出し(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#call" },
        { label: "cancelautomode", description: "「自動的に読み進む」の解除(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#cancelautomode" },
        { label: "cancelskip", description: "スキップの解除(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#cancelskip" },
        { label: "cancelvideoevent", description: "ピリオドイベントの解除(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#cancelvideoevent" },
        { label: "cancelvideosegloop", description: "ビデオのセグメントループ再生の解除(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#cancelvideosegloop" },
        { label: "cclick", description: "クリック待ち解除(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#cclick" },
        { label: "ch", description: "文字を表示する(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#ch" },
        { label: "checkbox", description: "チェックボックスの作成(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#checkbox" },
        { label: "clearbgmlabel", description: "BGM のラベル通過処理の解除(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#clearbgmlabel" },
        { label: "clearbgmstop", description: "BGM の停止処理の解除(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#clearbgmstop" },
        { label: "clearsysvar", description: "システム変数の全消去(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#clearsysvar" },
        { label: "clearvar", description: "ゲーム変数の全消去(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#clearvar" },
        { label: "clearvideolayer", description: "ビデオレイヤ解除(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#clearvideolayer" },
        { label: "click", description: "クリック待ちジャンプ(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#click" },
        { label: "clickskip", description: "クリックスキップの設定(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#clickskip" },
        { label: "close", description: "ウィンドウを閉じる(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#close" },
        { label: "cm", description: "すべてのメッセージレイヤのクリア(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#cm" },
        { label: "commit", description: "フォーム内容の確定(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#commit" },
        { label: "copybookmark", description: "栞のコピー(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#copybookmark" },
        { label: "copylay", description: "レイヤ情報のコピー(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#copylay" },
        { label: "ct", description: "メッセージレイヤのリセット(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#ct" },
        { label: "ctimeout", description: "タイムアウト待ち解除(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#ctimeout" },
        { label: "current", description: "操作対象のメッセージレイヤの指定(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#current" },
        { label: "cursor", description: "マウスカーソルの変更(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#cursor" },
        { label: "cwheel", description: "ホイール待ち解除(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#cwheel" },
        { label: "deffont", description: "デフォルトの文字属性設定(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#deffont" },
        { label: "defstyle", description: "デフォルトのスタイルの設定(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#defstyle" },
        { label: "delay", description: "文字の表示速度の設定(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#delay" },
        { label: "disablestore", description: "栞の機能の一時的な使用不可(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#disablestore" },
        { label: "edit", description: "単一行エディットの作成(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#edit" },
        { label: "else", description: "if の中身が実行されなかったときに実行(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#else" },
        { label: "elsif", description: "それまでの if の中身が実行されていなかったときに、条件付きで実行(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#elsif" },
        { label: "emb", description: "式評価結果の埋め込み(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#emb" },
        { label: "endhact", description: "メッセージ履歴アクションの終了(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#endhact" },
        { label: "endif", description: "条件によりシナリオを実行(の終了)(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#endif" },
        { label: "endignore", description: "条件によりシナリオを無視(の終了)(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#endignore" },
        { label: "endindent", description: "インデントの解除(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#endindent" },
        { label: "endlink", description: "ハイパーリンク(の終了)(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#endlink" },
        { label: "endmacro", description: "マクロの記述(の終了)(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#endmacro" },
        { label: "endnowait", description: "文字表示ノーウェイト(の終了)(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#endnowait" },
        { label: "endscript", description: "TJS スクリプトの記述(の終了)(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#endscript" },
        { label: "er", description: "メッセージレイヤの文字の消去(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#er" },
        { label: "erasebookmark", description: "栞の消去(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#erasebookmark" },
        { label: "erasemacro", description: "マクロの消去(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#erasemacro" },
        { label: "eval", description: "式の評価(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#eval" },
        { label: "fadebgm", description: "BGMのフェード(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#fadebgm" },
        { label: "fadeinbgm", description: "フェードインしながらのBGM再生開始(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#fadeinbgm" },
        { label: "fadeinse", description: "効果音のフェードイン再生(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#fadeinse" },
        { label: "fadeoutbgm", description: "BGMのフェードアウト(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#fadeoutbgm" },
        { label: "fadeoutse", description: "効果音のフェードアウト(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#fadeoutse" },
        { label: "fadepausebgm", description: "BGM 演奏のフェードアウトしながらの一時停止(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#fadepausebgm" },
        { label: "fadese", description: "効果音のフェード(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#fadese" },
        { label: "font", description: "文字属性設定(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#font" },
        { label: "freeimage", description: "レイヤ画像の解放(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#freeimage" },
        { label: "glyph", description: "クリック待ち記号の指定(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#glyph" },
        { label: "goback", description: "前に戻る(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#goback" },
        { label: "gotostart", description: "最初に戻る(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#gotostart" },
        { label: "graph", description: "インライン画像表示(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#graph" },
        { label: "hact", description: "メッセージ履歴アクション(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#hact" },
        { label: "hch", description: "縦中横を表示する(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#hch" },
        { label: "hidemessage", description: "メッセージを消す(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#hidemessage" },
        { label: "history", description: "メッセージ履歴の設定(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#history" },
        { label: "hr", description: "メッセージ履歴の改行/改ページ(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#hr" },
        { label: "if", description: "条件によりシナリオを実行(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#if" },
        { label: "ignore", description: "条件によりシナリオを無視(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#ignore" },
        { label: "image", description: "画像の読み込み(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#image" },
        { label: "indent", description: "インデントの設定(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#indent" },
        { label: "input", description: "文字列の入力(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#input" },
        { label: "iscript", description: "TJS スクリプトの記述(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#iscript" },
        { label: "jump", description: "シナリオのジャンプ(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#jump" },
        { label: "l", description: "行末クリック待ち(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#l" },
        { label: "laycount", description: "レイヤの数の変更(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#laycount" },
        { label: "layopt", description: "レイヤの属性(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#layopt" },
        { label: "link", description: "ハイパーリンク(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#link" },
        { label: "load", description: "栞の読み込み(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#load" },
        { label: "loadplugin", description: "プラグインの読み込み(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#loadplugin" },
        { label: "locate", description: "文字表示位置の指定(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#locate" },
        { label: "locklink", description: "リンクのロック(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#locklink" },
        { label: "locksnapshot", description: "スナップショットのロック(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#locksnapshot" },
        { label: "macro", description: "マクロの記述(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#macro" },
        { label: "mapaction", description: "クリッカブルマップ用領域アクション定義ファイルの指定(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#mapaction" },
        { label: "mapdisable", description: "クリッカブルマップの無効化(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#mapdisable" },
        { label: "mapimage", description: "クリッカブルマップ用領域画像の指定(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#mapimage" },
        { label: "mappfont", description: "レンダリング済みフォントの割り当て(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#mappfont" },
        { label: "move", description: "レイヤの自動移動(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#move" },
        { label: "nextskip", description: "「次の選択肢まですすむ」の設定(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#nextskip" },
        { label: "nowait", description: "文字表示ノーウェイト(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#nowait" },
        { label: "openvideo", description: "ビデオ/SWFの再生準備(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#openvideo" },
        { label: "p", description: "改ページクリック待ち(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#p" },
        { label: "pausebgm", description: "BGM 演奏の一時停止(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#pausebgm" },
        { label: "pausevideo", description: "ビデオの一時停止(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#pausevideo" },
        { label: "pimage", description: "画像の部分追加読み込み(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#pimage" },
        { label: "playbgm", description: "BGM の演奏(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#playbgm" },
        { label: "playse", description: "効果音の再生(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#playse" },
        { label: "playvideo", description: "ビデオ/SWFの再生(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#playvideo" },
        { label: "position", description: "メッセージレイヤの属性(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#position" },
        { label: "preparevideo", description: "ビデオの再生準備(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#preparevideo" },
        { label: "ptext", description: "レイヤへの文字描画(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#ptext" },
        { label: "quake", description: "画面を揺らす(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#quake" },
        { label: "r", description: "改行する(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#r" },
        { label: "rclick", description: "右クリックの設定(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#rclick" },
        { label: "record", description: "通過記録を行う(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#record" },
        { label: "resetfont", description: "文字属性をデフォルトに戻す(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#resetfont" },
        { label: "resetstyle", description: "スタイルをデフォルトに戻す(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#resetstyle" },
        { label: "resetwait", description: "ウェイトの初期化(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#resetwait" },
        { label: "resumebgm", description: "BGM 演奏の再開(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#resumebgm" },
        { label: "resumevideo", description: "ビデオ再生の再開(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#resumevideo" },
        { label: "return", description: "サブルーチンから戻る(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#return" },
        { label: "rewindvideo", description: "ビデオの巻き戻し(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#rewindvideo" },
        { label: "ruby", description: "ルビ指定(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#ruby" },
        { label: "s", description: "停止する(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#s" },
        { label: "save", description: "栞の保存(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#save" },
        { label: "seopt", description: "効果音の設定(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#seopt" },
        { label: "setbgmlabel", description: "BGM のラベル通過処理の登録(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#setbgmlabel" },
        { label: "setbgmstop", description: "BGM の停止処理の登録(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#setbgmstop" },
        { label: "showhistory", description: "メッセージ履歴の表示(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#showhistory" },
        { label: "startanchor", description: "「最初に戻る」の有効・無効(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#startanchor" },
        { label: "stopbgm", description: "BGM 演奏の停止(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#stopbgm" },
        { label: "stopmove", description: "レイヤの自動移動の停止(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#stopmove" },
        { label: "stopquake", description: "画面揺らしの停止(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#stopquake" },
        { label: "stopse", description: "効果音再生の停止(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#stopse" },
        { label: "stoptrans", description: "レイヤのトランジションの停止(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#stoptrans" },
        { label: "stopvideo", description: "ビデオ/SWF再生の停止(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#stopvideo" },
        { label: "store", description: "栞機能の設定(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#store" },
        { label: "style", description: "スタイルの設定(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#style" },
        { label: "tempload", description: "栞のメモリ上からの読み込み(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#tempload" },
        { label: "tempsave", description: "栞のメモリ上への保存(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#tempsave" },
        { label: "timeout", description: "タイムアウト待ちジャンプ(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#timeout" },
        { label: "title", description: "タイトル指定(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#title" },
        { label: "trace", description: "コンソールへ値の出力(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#trace" },
        { label: "trans", description: "レイヤのトランジション(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#trans" },
        { label: "unlocklink", description: "リンクのロックの解除(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#unlocklink" },
        { label: "unlocksnapshot", description: "スナップショットのロックの解除(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#unlocksnapshot" },
        { label: "video", description: "ビデオ/SWF表示領域の属性を指定(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#video" },
        { label: "videoevent", description: "ピリオドイベントの発生(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#videoevent" },
        { label: "videolayer", description: "ビデオレイヤ設定(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#videolayer" },
        { label: "videosegloop", description: "ビデオのセグメントループ再生(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#videosegloop" },
        { label: "wa", description: "アニメーションの停止待ち(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#wa" },
        { label: "wait", description: "ウェイトを入れる(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#wait" },
        { label: "waitclick", description: "クリックを待つ(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#waitclick" },
        { label: "waittrig", description: "トリガを待つ(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#waittrig" },
        { label: "wb", description: "BGM フェードの終了待ち(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#wb" },
        { label: "wc", description: "文字数分のウェイトを入れる(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#wc" },
        { label: "wf", description: "効果音フェードの終了待ち(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#wf" },
        { label: "wheel", description: "ホイール待ちジャンプ(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#wheel" },
        { label: "wl", description: "BGM 再生の終了待ち(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#wl" },
        { label: "wm", description: "自動移動の終了待ち(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#wm" },
        { label: "wp", description: "ビデオピリオドイベント待ち(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#wp" },
        { label: "wq", description: "画面揺らしの終了待ち(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#wq" },
        { label: "ws", description: "効果音再生の終了待ち(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#ws" },
        { label: "wt", description: "トランジションの終了待ち(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#wt" },
        { label: "wv", description: "ビデオ再生の終了待ち(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#wv" },
        { label: "xchgbgm", description: "BGM を入れ替える(KAG3)", url: "https://krkrz.github.io/krkr2doc/kag3doc/contents/Tags.html#xchgbgm" },
    ];
    private readonly kagexReferenceMap: QuickPickItemWithURL[] = [
        { label: "action", description: "アクションの開始(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#action" },
        { label: "animstart", description: "アニメーションの開始(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#animstart" },
        { label: "animstop", description: "アニメーションの停止(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#animstop" },
        { label: "autoindent", description: "自動インデントの設定(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#autoindent" },
        { label: "autolabel", description: "自動ラベルの挿入(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#autolabel" },
        { label: "autowc", description: "自動ウェイト(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#autowc" },
        { label: "backlay", description: "レイヤ情報の表ページから裏ページへのコピー(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#backlay" },
        { label: "beginskip", description: "特殊スキップ(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#beginskip" },
        { label: "bgmopt", description: "BGM の設定(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#bgmopt" },
        { label: "bradd", description: "分岐の登録(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#bradd" },
        { label: "branch", description: "分岐の実行(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#branch" },
        { label: "brdone", description: "分岐後の合流(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#brdone" },
        { label: "button", description: "グラフィカルボタンの作成(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#button" },
        { label: "call", description: "サブルーチンの呼び出し(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#call" },
        { label: "cancelautomode", description: "オートモードの解除(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#cancelautomode" },
        { label: "cancelnowaitmode", description: "強制オートモードの解除(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#cancelnowaitmode" },
        { label: "cancelskip", description: "スキップの解除(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#cancelskip" },
        { label: "cancelvideoevent", description: "ピリオドイベントの解除(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#cancelvideoevent" },
        { label: "cancelvideosegloop", description: "ビデオのセグメントループ再生の解除(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#cancelvideosegloop" },
        { label: "ch", description: "文字を表示する(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#ch" },
        { label: "checkbox", description: "チェックボックスの作成(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#checkbox" },
        { label: "clearallmacro", description: "マクロの全消去(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#clearallmacro" },
        { label: "clearbgmlabel", description: "BGM のラベル通過処理の解除(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#clearbgmlabel" },
        { label: "clearbgmstop", description: "BGM の停止処理の解除(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#clearbgmstop" },
        { label: "clearhistory", description: "メッセージ履歴の消去(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#clearhistory" },
        { label: "clearlayers", description: "レイヤの全消去(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#clearlayers" },
        { label: "clearplaytime", description: "プレイ時間の消去(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#clearplaytime" },
        { label: "clearsysvar", description: "システム変数の全消去(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#clearsysvar" },
        { label: "clearvar", description: "ゲーム変数の全消去(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#clearvar" },
        { label: "clearvideolayer", description: "ビデオレイヤ解除(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#clearvideolayer" },
        { label: "click", description: "クリック待ちジャンプ(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#click" },
        { label: "clickskip", description: "クリックスキップの設定(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#clickskip" },
        { label: "close", description: "ウィンドウを閉じる(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#close" },
        { label: "cm", description: "すべてのメッセージレイヤの消去(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#cm" },
        { label: "commit", description: "フォーム内容の確定(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#commit" },
        { label: "copybookmark", description: "栞のコピー(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#copybookmark" },
        { label: "copylay", description: "レイヤ情報のコピー(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#copylay" },
        { label: "craftername", description: "名前表記直後の改行の無視(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#craftername" },
        { label: "csysbutton", description: "システムボタンの消去(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#csysbutton" },
        { label: "ct", description: "メッセージレイヤのリセット(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#ct" },
        { label: "ctimeout", description: "タイムアウト待ち解除(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#ctimeout" },
        { label: "current", description: "操作対象のメッセージレイヤの指定(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#current" },
        { label: "cursor", description: "マウスカーソルの変更(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#cursor" },
        { label: "cwheel", description: "ホイール待ち解除(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#cwheel" },
        { label: "deffont", description: "デフォルトの文字属性設定(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#deffont" },
        { label: "defstyle", description: "デフォルトのスタイルの設定(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#defstyle" },
        { label: "delay", description: "文字の表示速度の設定(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#delay" },
        { label: "disablestore", description: "栞の機能の一時的な使用不可(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#disablestore" },
        { label: "edit", description: "単一行エディットの作成(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#edit" },
        { label: "else", description: "if の中身が実行されなかったときに実行(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#else" },
        { label: "elsif", description: "それまでの if の中身が実行されていなかったときに、条件付きで実行(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#elsif" },
        { label: "emb", description: "式評価結果の埋め込み(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#emb" },
        { label: "endhact", description: "メッセージ履歴アクションの終了(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#endhact" },
        { label: "endif", description: "条件によりシナリオを実行(の終了)(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#endif" },
        { label: "endignore", description: "条件によりシナリオを無視(の終了)(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#endignore" },
        { label: "endindent", description: "インデントの解除(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#endindent" },
        { label: "endlink", description: "ハイパーリンク(の終了)(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#endlink" },
        { label: "endmacro", description: "マクロの記述(の終了)(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#endmacro" },
        { label: "endnowait", description: "文字表示ノーウェイト(の終了)(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#endnowait" },
        { label: "endrecollection", description: "回想の終了(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#endrecollection" },
        { label: "endscript", description: "TJS スクリプトの記述(の終了)(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#endscript" },
        { label: "endskip", description: "特殊スキップ(の終了)(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#endskip" },
        { label: "er", description: "メッセージレイヤの文字の消去(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#er" },
        { label: "erafterpage", description: "メッセージの自動消去(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#erafterpage" },
        { label: "erasebookmark", description: "栞の消去(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#erasebookmark" },
        { label: "erasemacro", description: "マクロの消去(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#erasemacro" },
        { label: "eval", description: "式の評価(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#eval" },
        { label: "fadebgm", description: "BGM のフェード(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#fadebgm" },
        { label: "fadeinbgm", description: "BGM のフェードイン(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#fadeinbgm" },
        { label: "fadeinse", description: "効果音のフェードイン(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#fadeinse" },
        { label: "fadeoutbgm", description: "BGM のフェードアウト(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#fadeoutbgm" },
        { label: "fadeoutse", description: "効果音のフェードアウト(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#fadeoutse" },
        { label: "fadepausebgm", description: "BGM 演奏のフェードアウトしながらの一時停止(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#fadepausebgm" },
        { label: "fadese", description: "効果音のフェード(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#fadese" },
        { label: "font", description: "文字属性設定(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#font" },
        { label: "forelay", description: "レイヤ情報の裏ページから表ページへのコピー(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#forelay" },
        { label: "freeimage", description: "レイヤ画像の解放(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#freeimage" },
        { label: "freesnapshot", description: "スナップショットのロックの強制解除(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#freesnapshot" },
        { label: "func", description: "関数の呼び出し(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#func" },
        { label: "glyph", description: "クリック待ち記号の指定(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#glyph" },
        { label: "goback", description: "前に戻る(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#goback" },
        { label: "gotostart", description: "最初に戻る(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#gotostart" },
        { label: "graph", description: "インライン画像表示(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#graph" },
        { label: "hact", description: "メッセージ履歴アクション(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#hact" },
        { label: "hch", description: "縦中横を表示する(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#hch" },
        { label: "hidemessage", description: "メッセージを隠す(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#hidemessage" },
        { label: "history", description: "メッセージ履歴の設定(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#history" },
        { label: "hr", description: "メッセージ履歴の改行/改ページ(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#hr" },
        { label: "if", description: "条件によりシナリオを実行(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#if" },
        { label: "ignore", description: "条件によりシナリオを無視(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#ignore" },
        { label: "image", description: "画像の読み込み(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#image" },
        { label: "img", description: "画像の読み込み(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#img" },
        { label: "indent", description: "インデントの設定(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#indent" },
        { label: "input", description: "文字列の入力(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#input" },
        { label: "iscript", description: "TJS スクリプトの記述(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#iscript" },
        { label: "jump", description: "シナリオのジャンプ(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#jump" },
        { label: "l", description: "行末クリック待ち(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#l" },
        { label: "layback", description: "表示レベルが同じレイヤの中で最背面に(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#layback" },
        { label: "laycount", description: "レイヤの数の変更(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#laycount" },
        { label: "layfront", description: "表示レベルが同じレイヤの中で最前面に(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#layfront" },
        { label: "laylevel", description: "表示レベルの変更(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#laylevel" },
        { label: "layopt", description: "(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#layopt" },
        { label: "linemode", description: "ラインモードの設定(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#linemode" },
        { label: "link", description: "ハイパーリンク(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#link" },
        { label: "load", description: "栞の読み込み(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#load" },
        { label: "loadplugin", description: "プラグインの読み込み(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#loadplugin" },
        { label: "locate", description: "文字表示位置の指定(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#locate" },
        { label: "locklink", description: "リンクのロック(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#locklink" },
        { label: "locksnapshot", description: "スナップショットのロック(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#locksnapshot" },
        { label: "ltbegin", description: "画面切り替えの開始(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#ltbegin" },
        { label: "ltend", description: "画面切り替えの終了(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#ltend" },
        { label: "macro", description: "マクロの記述(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#macro" },
        { label: "mapaction", description: "クリッカブルマップ用領域アクション定義ファイルの指定(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#mapaction" },
        { label: "mapdisable", description: "クリッカブルマップの無効化(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#mapdisable" },
        { label: "mapimage", description: "クリッカブルマップ用領域画像の指定(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#mapimage" },
        { label: "mappfont", description: "レンダリング済みフォントの割り当て(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#mappfont" },
        { label: "move", description: "レイヤの自動移動(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#move" },
        { label: "mseladd", description: "マップ選択肢の登録(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#mseladd" },
        { label: "mselbutton", description: "マップ選択肢のボタン情報の登録(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#mselbutton" },
        { label: "mselect", description: "マップ選択肢の実行(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#mselect" },
        { label: "mselinit", description: "マップ選択肢の初期化(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#mselinit" },
        { label: "mselopt", description: "マップ選択肢の属性(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#mselopt" },
        { label: "mselpos", description: "マップ選択肢の場所情報の登録(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#mselpos" },
        { label: "next", description: "シナリオのジャンプ(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#next" },
        { label: "nextskip", description: "「次の選択肢まですすむ」の設定(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#nextskip" },
        { label: "noeffect", description: "トランジションの速さ設定の無効化(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#noeffect" },
        { label: "noer", description: "メッセージの自動消去の抑制(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#noer" },
        { label: "nor", description: "改行の機能の抑制(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#nor" },
        { label: "notextmode", description: "文字出力の設定(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#notextmode" },
        { label: "nowait", description: "文字表示ノーウェイト(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#nowait" },
        { label: "nowaitmode", description: "強制オートモード(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#nowaitmode" },
        { label: "openvideo", description: "ビデオの再生準備(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#openvideo" },
        { label: "p", description: "改ページクリック待ち(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#p" },
        { label: "panel", description: "パネルレイヤの表示(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#panel" },
        { label: "parse", description: "(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#parse" },
        { label: "pausebgm", description: "BGM 再生の一時停止(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#pausebgm" },
        { label: "pausevideo", description: "ビデオの一時停止(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#pausevideo" },
        { label: "pimage", description: "画像の部分追加読み込み(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#pimage" },
        { label: "playbgm", description: "BGM の再生(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#playbgm" },
        { label: "playse", description: "効果音の再生(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#playse" },
        { label: "playvideo", description: "ビデオの再生(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#playvideo" },
        { label: "position", description: "メッセージレイヤの属性(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#position" },
        { label: "preparevideo", description: "ビデオの再生準備(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#preparevideo" },
        { label: "ptext", description: "レイヤへの文字描画(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#ptext" },
        { label: "quake", description: "画面を揺らす(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#quake" },
        { label: "r", description: "改行する(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#r" },
        { label: "rclick", description: "右クリックの設定(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#rclick" },
        { label: "recollection", description: "回想の実行(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#recollection" },
        { label: "record", description: "通過記録を行う(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#record" },
        { label: "resetfont", description: "文字属性をデフォルトに戻す(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#resetfont" },
        { label: "resetstyle", description: "スタイルをデフォルトに戻す(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#resetstyle" },
        { label: "resetwait", description: "ウェイトの初期化(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#resetwait" },
        { label: "resumebgm", description: "BGM 再生の再開(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#resumebgm" },
        { label: "resumevideo", description: "ビデオ再生の再開(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#resumevideo" },
        { label: "return", description: "サブルーチンから戻る(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#return" },
        { label: "rewindvideo", description: "ビデオの巻き戻し(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#rewindvideo" },
        { label: "ruby", description: "ルビ指定(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#ruby" },
        { label: "s", description: "停止する(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#s" },
        { label: "save", description: "栞の保存(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#save" },
        { label: "seladd", description: "選択肢の登録(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#seladd" },
        { label: "seldone", description: "選択肢後の合流(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#seldone" },
        { label: "select", description: "選択肢の実行(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#select" },
        { label: "selopt", description: "選択肢の属性(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#selopt" },
        { label: "seopt", description: "効果音の設定(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#seopt" },
        { label: "set", description: "変数の設定(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#set" },
        { label: "setbgmlabel", description: "BGM のラベル通過処理の登録(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#setbgmlabel" },
        { label: "setbgmstop", description: "BGM の停止処理の登録(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#setbgmstop" },
        { label: "showhistory", description: "メッセージ履歴の表示(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#showhistory" },
        { label: "showwait", description: "ウェイト時間の表示(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#showwait" },
        { label: "slider", description: "スライダの作成(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#slider" },
        { label: "startanchor", description: "「最初に戻る」の有効・無効(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#startanchor" },
        { label: "stopaction", description: "アクションの停止(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#stopaction" },
        { label: "stopbgm", description: "BGM 再生の停止(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#stopbgm" },
        { label: "stopmove", description: "レイヤの自動移動の停止(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#stopmove" },
        { label: "stopquake", description: "画面揺らしの停止(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#stopquake" },
        { label: "stoprecollection", description: "回想の中止(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#stoprecollection" },
        { label: "stopse", description: "効果音再生の停止(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#stopse" },
        { label: "stoptrans", description: "レイヤのトランジションの停止(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#stoptrans" },
        { label: "stopvideo", description: "ビデオ再生の停止(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#stopvideo" },
        { label: "store", description: "栞機能の設定(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#store" },
        { label: "style", description: "スタイルの設定(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#style" },
        { label: "syncmsg", description: "メッセージレイヤの表ページから裏ページへのコピー(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#syncmsg" },
        { label: "sysbutton", description: "システムボタンの作成(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#sysbutton" },
        { label: "sysuiload", description: "(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#sysuiload" },
        { label: "td", description: "遅延実行ラベルの登録(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#td" },
        { label: "tempload", description: "栞のメモリ上からの読み込み(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#tempload" },
        { label: "tempsave", description: "栞のメモリ上への保存(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#tempsave" },
        { label: "timeout", description: "タイムアウト待ちジャンプ(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#timeout" },
        { label: "title", description: "タイトル指定(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#title" },
        { label: "trace", description: "コンソールへ値の出力(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#trace" },
        { label: "trans", description: "レイヤのトランジション(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#trans" },
        { label: "uiload", description: "(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#uiload" },
        { label: "unlocklink", description: "リンクのロックの解除(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#unlocklink" },
        { label: "unlocksnapshot", description: "スナップショットのロックの解除(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#unlocksnapshot" },
        { label: "video", description: "ビデオ表示領域の属性を指定(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#video" },
        { label: "videoevent", description: "ピリオドイベントの発生(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#videoevent" },
        { label: "videolayer", description: "ビデオレイヤ設定(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#videolayer" },
        { label: "videosegloop", description: "ビデオのセグメントループ再生(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#videosegloop" },
        { label: "voice", description: "(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#voice" },
        { label: "wa", description: "アニメーションの停止待ち(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#wa" },
        { label: "wact", description: "アクションの終了待ち(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#wact" },
        { label: "wait", description: "ウェイトを入れる(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#wait" },
        { label: "waitclick", description: "クリックを待つ(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#waitclick" },
        { label: "waittrig", description: "トリガを待つ(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#waittrig" },
        { label: "waituntil", description: "時間原点からのウェイトを入れる(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#waituntil" },
        { label: "wat", description: "アクションとトランジションの終了待ち(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#wat" },
        { label: "wb", description: "BGM フェードの終了待ち(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#wb" },
        { label: "wbl", description: "BGM のラベル通過待ち(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#wbl" },
        { label: "wc", description: "文字数分のウェイトを入れる(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#wc" },
        { label: "wd", description: "遅延実行ラベル待ち(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#wd" },
        { label: "wf", description: "効果音フェードの終了待ち(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#wf" },
        { label: "wheel", description: "ホイール待ちジャンプ(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#wheel" },
        { label: "wl", description: "BGM 再生の終了待ち(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#wl" },
        { label: "wm", description: "自動移動の終了待ち(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#wm" },
        { label: "wp", description: "ビデオのイベント待ち(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#wp" },
        { label: "wq", description: "画面揺らしの終了待ち(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#wq" },
        { label: "ws", description: "効果音再生の終了待ち(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#ws" },
        { label: "wt", description: "トランジションの終了待ち(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#wt" },
        { label: "wv", description: "ビデオ再生の終了待ち(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#wv" },
        { label: "xchgbgm", description: "BGM を入れ替える(KAGEX)", url: "https://biscrat.com/krkr/docs/kagex/contents/Tags.html#xchgbgm" },
    ];

    private readonly pickItems: QuickPickItemWithURL[] = [];

    public constructor() {
        this.loadConfiguration();
    }

    private loadConfiguration() {
        const config = vscode.workspace.getConfiguration("kagex").referencePromptEnable;
        const check = (key: string, def: boolean): boolean => {
            if (def) {
                return config === undefined || config[key] === undefined || config[key];
            } else {
                return config !== undefined && config[key] !== undefined && config[key];
            }
        };

        this.pickItems.length = 0;
        if (check("kag3", false)) { Array.prototype.push.apply(this.pickItems, this.kag3ReferenceMap); }
        if (check("kagex", true)) { Array.prototype.push.apply(this.pickItems, this.kagexReferenceMap); }
        this.pickItems.sort(this.compare);
    }

    private compare(a: vscode.QuickPickItem, b: vscode.QuickPickItem): number {
        const aStr = a.label + a.description;
        const bStr = b.label + b.description;
        return aStr > bStr ? 1 : aStr === bStr ? 0 : -1;
    }

    public showPrompt() {
        const options: vscode.QuickPickOptions = {
            "placeHolder": "Which reference will you open?",
            "matchOnDescription": true
        };

        vscode.window.showQuickPick<QuickPickItemWithURL>(this.pickItems, options).then(item => {
            if (item === undefined) { return; }
            vscode.commands.executeCommand('vscode.open', vscode.Uri.parse(item.url));
        });
    }

    public onDidChangeConfiguration() {
        this.loadConfiguration();
    }
}

